/* global WEBPACK_API_SECRET, WEBPACK_SITE_URL, WEBPACK_API_URL, WEBPACK_MONGO_URL, WEBPACK_ACCESS_TOKEN_TTL, WEBPACK_SIGNIN_TOKEN_TTL, WEBPACK_FROM_EMAIL, WEBPACK_SUPERADMIN_EMAIL, WEBPACK_SEED, WEBPACK_S3_BUCKET */

module.exports = {
  secret: WEBPACK_API_SECRET,
  site: WEBPACK_SITE_URL,
  host: WEBPACK_API_URL,
  mongo: WEBPACK_MONGO_URL,
  accessTokenTTL: WEBPACK_ACCESS_TOKEN_TTL,
  signInTokenTTL: WEBPACK_SIGNIN_TOKEN_TTL,
  from: WEBPACK_FROM_EMAIL,
  superadmin: WEBPACK_SUPERADMIN_EMAIL,
  seed: WEBPACK_SEED,
  s3Bucket: WEBPACK_S3_BUCKET,
  aws: {
    accessKey: process.env.AWS_ACCESS_TOKEN,
    secretKey: process.env.AWS_SECRET_TOKEN,
    region: process.env.REGION || 'us-east-1',
  },
}
