const COSTA_RICA_TREES = [
  'abejón',
  'aceituno de Guanacaste',
  'acerola',
  'achiote',
  'achiotillo',
  'aguacate',
  'aguacatillo',
  'ahuehuete',
  'akí',
  'albahaquillo de Puriscal',
  'almendro de Madagascar',
  'almendro de montaña',
  'almendro de playa',
  'almendro de río',
  'amarillón',
  'anacahuita',
  'anono',
  'anono amarillo',
  'araucaria excelsa',
  'arazá',
  'árbol de fuego',
  'arco',
  'bala de cañón',
  'balsa',
  'bijarro',
  'brasil',
  'burío',
  'cabello de ángel',
  'cacao',
  'cachá',
  'cachimbo',
  'cachito',
  'caimitillo',
  'caimito',
  'camíbar',
  'candelero',
  'candelillo',
  'canelo',
  'caña fístula',
  'caoba hondureña',
  'caobilla',
  'capulín de comer',
  'carambola',
  'carao',
  'carao amarillo',
  'carboncillo',
  'carboncillo',
  'caregre',
  'cas',
  'cascarillo',
  'casco de venado',
  'casco de venado',
  'casia de Java',
  'casuarinas',
  'cebo',
  'cedro amargo',
  'cedro bateo',
  'cedro de la India',
  'cedro dulce',
  'cedro real',
  'ceiba',
  'ceiba pochote',
  'ceibo',
  'ceibo rosado',
  'cenízaro',
  'cerillo',
  'champaca',
  'chaperno negro',
  'chaya',
  'chicasquil',
  'chilamate colorado',
  'chilamate de río',
  'chilemuelo',
  'chirca',
  'chirraco',
  'ciprecillo',
  'cipresillo',
  'ciprés',
  'ciprés lorito',
  'cirrí blanco',
  'cirrí colorado',
  'cítricos',
  'cobrizo',
  'cocobolo',
  'colpachí',
  'conchudo',
  'copey',
  'coralillo',
  'corcho australiano',
  'cordoncillo',
  'cortez negro',
  'corteza amarilla',
  'cristóbal',
  'cuajilote',
  'curá',
  'curú',
  'dama',
  'danto',
  'escampa gallina',
  'espavel',
  'espino crucilla',
  'eucaliptos',
  'falso pimentero',
  'fresno mexicano',
  'fruta de pava',
  'fruta milagrosa',
  'gallinazo',
  'gandul',
  'gavilán',
  'granado real',
  'grano de oro',
  'gravilia',
  'guabos y cuajiniquiles',
  'guacamaya',
  'guachipelín',
  'guácimo',
  'guaitil',
  'guamacho',
  'guanacaste',
  'guanacaste blanco',
  'guapinol',
  'guarumos',
  'guastomate',
  'guayabo',
  'guayaba de mono',
  'guayabón',
  'guayacán real',
  'guayaquil',
  'guinda',
  'güísaro',
  'güitite',
  'higuerilla',
  'higuerones',
  'higuerón blanco ',
  'higuerón chumico',
  'higuerón paleto',
  'higuito',
  'hisopo',
  'hombre grande',
  'hormigo',
  'hule',
  'icaco',
  'iguano',
  'ilan-ilan',
  'indio desnudo',
  'jabillo',
  'jaboncillo',
  'jaboticaba',
  'jaca, jaquero',
  'jacaranda',
  'jamaica',
  'jaúl',
  'jazmín africano',
  'jicarito',
  'jícaro de playa',
  'jícaro guacal',
  'jobo',
  'jocote',
  'jorco',
  'juche',
  'klinki',
  'laurel',
  'laurel de la India',
  'laurel muñeco',
  'laurel negro',
  'leucaena',
  'liquidámbar',
  'limón criollo',
  'llama del bosque',
  'lorito',
  'limoncillo',
  'lorito',
  'macadamia',
  'madero negro',
  'madroño',
  'magnolias ticas',
  'magnolia grandiflora',
  'majagua',
  'malinche',
  'mamey',
  'mamón',
  'mandarina',
  'mango',
  'mangostan',
  'manú plátano',
  'manú negro',
  'manzanita',
  'manzana de agua',
  'manzana rosa',
  'mapuche',
  'marañón',
  'maría colorado',
  'matapalo',
  'matapulgas',
  'matasano',
  'mateares',
  'mirto',
  'mirto australiano',
  'mole',
  'moquillo',
  'mora',
  'morera',
  'murta',
  'nance',
  'nazarenillo',
  'naranjilla',
  'nazareno',
  'níspero chicle',
  'níspero japonés',
  'níspero zapotillo',
  'nogal negro',
  'noni',
  'nuez moscada',
  'ojoche',
  'ojoche colorado',
  'olla de mono',
  'olosapo',
  'orgullo de la India',
  'palanco',
  'palo verde',
  'papalán',
  'papaturro',
  'papiro',
  'paraíso',
  'pascuita',
  'pepenance',
  'pilón',
  'piracanto',
  'pino triste',
  'pirul',
  'pitanga',
  'pochote',
  'pompón rojo',
  'poponjoche',
  'poró africano',
  'poró blanco',
  'poró criollo',
  'poró gigante',
  'poro poro',
  'primavera',
  'purre',
  'quebracho',
  'quina',
  'raspaguacal',
  'ratoncillo',
  'reseda',
  'roble ',
  'roble encino',
  'roble sabana',
  'ron ron',
  'rondeletia',
  'rosa de Brasil',
  'rosa de monte',
  'salvia',
  'saúce',
  'saíno',
  'sangrillo',
  'sietecueros',
  'sombrilla australiana',
  'soncoya',
  'sonzapote',
  'sotacaballo',
  'supara',
  'tamarindo',
  'targuá sangregao',
  'tempate',
  'tempisque',
  'terciopelo',
  'tigüilote',
  'tirrá',
  'tomate de árbol',
  'trompito',
  'trueno',
  'tubú',
  'tucuico',
  'tuete',
  'uruca',
  'vainillo',
  'yas',
  'yos',
  'yuco',
  'yuplón',
  'zapote',
  'zapote negro',
  'zorrillo de comer'
]

module.exports = COSTA_RICA_TREES
